"""Change course_id to subject in Attendance

Revision ID: dfedec1d4364
Revises: 
Create Date: 2024-05-28 06:31:48.018659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfedec1d4364'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('attendance_ibfk_2', type_='foreignkey')
        batch_op.drop_column('course_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('attendance_ibfk_2', 'course', ['course_id'], ['id'])
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
